name: Changelog
on:
  push:
    branches: [ main ]
jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
          id: vars
          run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}