name: Changelog
on:
  push:
    branches: [ main ]
jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Execute update of README
        run: |
          echo ${{ github.event.pull_request.base.ref }}