name: Build README
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '38 16 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update README
      run: |-
        python build_readme.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "diane.delallee@gmail.com"
        git config --global user.name "dianedelallee"
        git add -A
        git commit -m "Updated content" || exit 0
        git push
